apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-volume
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp
    server: iga-dc-nas.example.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs01